# Generated by Django 2.0.4 on 2018-04-11 21:12
from django.db import migrations

# This migration used to copy each username and email into bcrypt hashes on
# Account for the encrypted login backend. That backend was removed and 0006
# drops the columns, so there is nothing to copy any more.


class Migration(migrations.Migration):

    dependencies = [("accounts", "0003_auto_20190607_1540")]

    operations = []
