# Generated by Django 2.0.4 on 2018-04-11 21:12
from django.db import migrations

# This migration used to append ":unsafe" to every username and email so only
# the encrypted login backend could find them. That backend was removed; 0006
# strips the suffix from databases that already ran the old version.


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_encrypt_user_data")]

    operations = []
