# Generated by Django 5.2.17 on 2026-10-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0040_auto_20171215_0302"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecordHistorical",
        ),
    ]
