# Generated by Django 5.2.17 on 2026-10-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0041_delete_recordhistorical'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredPassphrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('report_uuid', models.UUIDField()),
                ('encrypted_passphrase', models.BinaryField()),
                ('used', models.DateTimeField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session_key', 'report_uuid'), name='unique_session_report')],
            },
        ),
    ]
