# Generated by Django 5.2.17 on 2026-10-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0042_storedpassphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_identifier', models.BinaryField()),
                ('site_id', models.IntegerField()),
                ('admin_email_template', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_identifier', models.BinaryField()),
                ('site_id', models.IntegerField()),
                ('admin_email_template', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('authority_notified', models.BooleanField(default=False)),
                ('owners_notified', models.BooleanField(default=False)),
                ('callisto_notified', models.BooleanField(default=False)),
                ('completed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('match_reports', models.ManyToManyField(to='delivery.matchreport')),
            ],
        ),
    ]
